import { readFileSync } from "node:fs";
import path from "node:path";

import type { Program } from "@prisma/client";
import { jsPDF } from "jspdf";

import { repairPotentialMojibake } from "@/lib/programs/normalize";
import { defaultPdfVisibilitySettings, type PdfVisibilitySettings } from "@/lib/programs/pdf-visibility";

type PrintableProgram = Pick<
  Program,
  | "programName"
  | "universityName"
  | "programDegree"
  | "language"
  | "campus"
  | "academicYear"
  | "semester"
  | "quotaFull"
  | "currencyType"
  | "tuitionFee"
  | "discountedTuitionFee"
  | "prepSchoolFee"
  | "cashPaymentFee"
  | "depositPrice"
>;

type PdfRenderOptions = {
  visibility?: PdfVisibilitySettings;
};

let arabicFontRegistered = false;
let arabicFontAvailable = true;

export function renderProgramsPdf(doc: jsPDF, programs: PrintableProgram[], options: PdfRenderOptions = {}) {
  ensureArabicFont(doc);

  const visibility = {
    ...defaultPdfVisibilitySettings,
    ...(options.visibility ?? {})
  };

  const sortedPrograms = [...programs].sort((a, b) => {
    const uni = cleanText(a.universityName).localeCompare(cleanText(b.universityName));

    if (uni !== 0) {
      return uni;
    }

    return cleanText(a.programName).localeCompare(cleanText(b.programName));
  });

  const cardsPerPage = 3;
  const totalPages = Math.max(1, Math.ceil(sortedPrograms.length / cardsPerPage));

  sortedPrograms.forEach((program, index) => {
    const pageIndex = Math.floor(index / cardsPerPage);
    const cardIndex = index % cardsPerPage;

    if (index > 0 && cardIndex === 0) {
      doc.addPage();
    }

    if (cardIndex === 0) {
      drawPageFrame(doc, {
        pageIndex,
        totalPages,
        totalPrograms: sortedPrograms.length
      });
    }

    drawProgramCard(doc, program, visibility, cardIndex);
  });
}

function drawPageFrame(
  doc: jsPDF,
  options: {
    pageIndex: number;
    totalPages: number;
    totalPrograms: number;
  }
) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginX = 24;
  const contentWidth = pageWidth - marginX * 2;

  doc.setFillColor(245, 248, 251);
  doc.setDrawColor(222, 230, 238);
  doc.roundedRect(marginX, 20, contentWidth, 40, 10, 10, "FD");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(21, 40, 61);
  doc.text("Student On Board | Program Catalog", marginX + 12, 44);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(78, 101, 124);
  doc.text("Grouped by university | Up to 3 courses per page", marginX + 12, 56);

  const pageBadge = `Page ${options.pageIndex + 1} / ${options.totalPages}`;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(54, 72, 92);
  doc.text(pageBadge, pageWidth - marginX - 12, 36, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.text(`${options.totalPrograms} program(s)`, pageWidth - marginX - 12, 50, { align: "right" });

  doc.setDrawColor(222, 230, 238);
  doc.line(marginX, pageHeight - 28, marginX + contentWidth, pageHeight - 28);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(120, 134, 149);
  doc.text("Generated by Student On Board", marginX, pageHeight - 14);
}

function drawProgramCard(doc: jsPDF, program: PrintableProgram, visibility: PdfVisibilitySettings, cardIndex: number) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const marginX = 24;
  const contentWidth = pageWidth - marginX * 2;
  const topY = 72;
  const footerTop = doc.internal.pageSize.getHeight() - 36;
  const cardGap = 12;
  const cardHeight = (footerTop - topY - cardGap * 2) / 3;
  const y = topY + cardIndex * (cardHeight + cardGap);

  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(214, 224, 235);
  doc.roundedRect(marginX, y, contentWidth, cardHeight, 10, 10, "FD");

  const university = visibility.showUniversity ? cleanText(program.universityName) : "University hidden";
  const title = visibility.showProgram ? cleanText(program.programName) : "Program hidden";
  const quota = visibility.showQuotaStatus ? (program.quotaFull ? "Quota full" : "Available") : null;

  drawSingleLineText(doc, university, marginX + 12, y + 16, contentWidth - 24, {
    fontSize: 12,
    color: [17, 47, 80],
    bold: true
  });

  if (quota) {
    const quotaText = `Status: ${quota}`;
    drawSingleLineText(doc, quotaText, marginX + contentWidth - 12, y + 16, contentWidth * 0.35, {
      fontSize: 8,
      color: [88, 106, 126],
      align: "right"
    });
  }

  drawSingleLineText(doc, title, marginX + 12, y + 34, contentWidth - 24, {
    fontSize: 11,
    color: [33, 41, 52],
    bold: true
  });

  doc.setDrawColor(232, 238, 245);
  doc.line(marginX + 12, y + 42, marginX + contentWidth - 12, y + 42);

  const currency = cleanText(program.currencyType, "USD");
  const entries: Array<[string, string]> = [];

  if (visibility.showDegree) entries.push(["Degree", cleanText(program.programDegree)]);
  if (visibility.showLanguage) entries.push(["Language", cleanText(program.language)]);
  if (visibility.showCampus) entries.push(["Campus", cleanText(program.campus)]);
  if (visibility.showAcademicYear) entries.push(["Year", cleanText(program.academicYear)]);
  if (visibility.showSemester) entries.push(["Semester", cleanText(program.semester)]);
  if (visibility.showCurrency) entries.push(["Currency", currency]);
  if (visibility.showTuitionFee) entries.push(["Tuition", printableCurrency(program.tuitionFee, currency)]);
  if (visibility.showDiscountedFee) entries.push(["Discounted", printableCurrency(program.discountedTuitionFee, currency)]);
  if (visibility.showPrepSchoolFee) entries.push(["Prep", printableCurrency(program.prepSchoolFee, currency)]);
  if (visibility.showCashPaymentFee) entries.push(["Cash", printableCurrency(program.cashPaymentFee, currency)]);
  if (visibility.showDepositPrice) entries.push(["Deposit", printableCurrency(program.depositPrice, currency)]);

  const leftEntries = entries.filter((_, index) => index % 2 === 0);
  const rightEntries = entries.filter((_, index) => index % 2 === 1);

  const colGap = 12;
  const colWidth = (contentWidth - 24 - colGap) / 2;
  const rowHeight = 12;
  const startY = y + 54;

  leftEntries.forEach(([label, value], index) => {
    const rowY = startY + index * rowHeight;
    drawMetaRow(doc, label, value, marginX + 12, rowY, colWidth);
  });

  rightEntries.forEach(([label, value], index) => {
    const rowY = startY + index * rowHeight;
    drawMetaRow(doc, label, value, marginX + 12 + colWidth + colGap, rowY, colWidth);
  });
}

function drawMetaRow(doc: jsPDF, label: string, value: string, x: number, y: number, width: number) {
  const labelWidth = width * 0.32;
  drawSingleLineText(doc, `${label}:`, x, y, labelWidth, {
    fontSize: 8,
    color: [100, 113, 129],
    bold: true
  });

  drawSingleLineText(doc, value, x + labelWidth + 2, y, width - labelWidth - 2, {
    fontSize: 8,
    color: [35, 46, 60]
  });
}

function drawSingleLineText(
  doc: jsPDF,
  value: string,
  x: number,
  y: number,
  maxWidth: number,
  options: {
    fontSize: number;
    color: [number, number, number];
    bold?: boolean;
    align?: "left" | "right";
  }
) {
  const processed = processArabicText(doc, value);
  const isArabic = containsArabic(value) && arabicFontAvailable;

  if (isArabic) {
    doc.setFont("ArialUnicode", "normal");
    doc.setR2L(true);
  } else {
    doc.setFont("helvetica", options.bold ? "bold" : "normal");
    doc.setR2L(false);
  }

  doc.setFontSize(options.fontSize);
  doc.setTextColor(...options.color);

  const alignedRight = options.align === "right";
  const rendered = ellipsizeText(doc, processed, maxWidth);

  doc.text(rendered, x, y, {
    align: alignedRight || isArabic ? "right" : "left"
  });

  doc.setR2L(false);
}

function ellipsizeText(doc: jsPDF, text: string, maxWidth: number) {
  if (doc.getTextWidth(text) <= maxWidth) {
    return text;
  }

  let output = text;

  while (output.length > 1 && doc.getTextWidth(`${output}...`) > maxWidth) {
    output = output.slice(0, -1);
  }

  return `${output}...`;
}

function ensureArabicFont(doc: jsPDF) {
  if (!arabicFontAvailable) {
    return;
  }

  if (arabicFontRegistered) {
    return;
  }

  try {
    const fontPath = path.join(process.cwd(), "public", "fonts", "ArialUnicode.ttf");
    const fontData = readFileSync(fontPath).toString("base64");

    doc.addFileToVFS("ArialUnicode.ttf", fontData);
    doc.addFont("ArialUnicode.ttf", "ArialUnicode", "normal");

    arabicFontRegistered = true;
  } catch {
    arabicFontAvailable = false;
  }
}

function cleanText(value: string | null | undefined, fallback = "Not specified") {
  const repaired = repairPotentialMojibake(value ?? "").replace(/\s+/g, " ").trim();
  return repaired || fallback;
}

function processArabicText(doc: jsPDF, value: string) {
  if (!containsArabic(value)) {
    return value;
  }

  const processArabic = (doc as unknown as { processArabic?: (text: string) => string }).processArabic;
  return processArabic ? processArabic(value) : value;
}

function containsArabic(value: string) {
  return /[\u0600-\u06FF]/.test(value);
}

function printableCurrency(value: number | null, currency: string) {
  if (value === null || value === undefined) {
    return "Not specified";
  }

  try {
    return new Intl.NumberFormat("en-US", {
      style: "currency",
      currency,
      maximumFractionDigits: value % 1 === 0 ? 0 : 2
    }).format(value);
  } catch {
    return `${value.toLocaleString("en-US")} ${currency}`.trim();
  }
}
